services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=prueba
      - POSTGRES_USER=prueba
      - POSTGRES_DB=prueba
    ports:
      - 5432:5432
  api:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=prueba
      - DATABASE_PASSWORD=prueba
      - DATABASE_NAME=prueba
